---

# tasks file for httpd
- name: Install httpd
  ansible.builtin.yum:
    name: httpd
    state: present

- name: Starting httpd service
  ansible.builtin.service:
    name: httpd
    state: started

- name: Copy the index.html file
  ansible.builtin.template:
    src: index.html
    dest: /var/www/html/index.html
  notify: Restart httpd
